### ISSUE TITLE
Using Materials to achieve infinite possibilities.

### ISSUE THREAD

**Issue by UTwelve** [brumenn/FlatNodes#10]
I noticed there is a material named "Box" in the FlatNodes/Materials folder, and I found that it has infinite possibilities.
Can all the styles of a node be used as a material?

> ![Box](https://i.imgur.com/rSb7vzl.gif)
> https://imgur.com/rSb7vzl

The plugin currently uses some PNG images. But if Materials are used instead, I can create things like rounded corner panels.

**Comment by brumenn** [comment]
Yes exactly, you can use material for everything slate related, and so stylize all the aspects of a node. 

But this is not what this plugin was intended for, and it will take a lot of work to have something nice and clean for many use cases. At first this plugin was just a slightly trick around png images, that's why I made it free on the marketplace. 

If you want something highly customizable, try other plugins on the marketplace, you will find something I'm sure.
