### ISSUE TITLE
When will 5.5 version be updated?

### ISSUE THREAD

**Issue by jamesmandrews** [brumenn/FlatNodes#18]

**Comment by IskandarAlex2** [comment]
So far, with my usage in 5.5, this plugin seems to do its job just fine, and I have yet to see any problems. However, it is bad when even the engine tells you the plugin is only made for 5.4 and whether you want to continue using it or disable it.

Although, since it is pretty much just an editor feature plugin I don't think it wouldn't be that much of a problem. On a side note, the author last committed to this repo 8 months ago, and looking at their profile shows no signs of activity so I highly doubt any updates on it unless they just came back online just to update it or someone fork it. We can only hope.

**Comment by brumenn** [comment]
I did it for the marketplace and forgot to do it for github, it should be ok now!

**Comment by IskandarAlex2** [comment]
![images](https://github.com/user-attachments/assets/7eefbf98-7f2f-4757-8524-8956840a2ec7)
